### ISSUE TITLE
how the program works?

### ISSUE THREAD

**Issue by afefCH** [omerwase/Image-Recognition-with-Spark-and-DL4J#1]
hello, i didn't understand how the program can working? you enter an image and it defined what is about?

**Comment by omerwase** [comment]
The program trains a convolutional neural network based on the images provided in the directory referenced by the -dirPath parameter. By default this directory is (not the best I realize):

private String dirPath = "sdcdata/sdcdata1000c/";

It splits the images in the directory into a training and testing set. After training on the training set it evaluates the networks performance on the testing set. 

If you are trying to understand the data pipeline I would recommend having a look at deeplearning4j's website (they have other useful tutorials as well):
https://deeplearning4j.org/tutorials#image-pipeline-tutorial
